import "@/styles/globals.css";
import { motion, AnimatePresence } from "framer-motion";
import { useRouter } from "next/router";
import { Amplify, Analytics } from "aws-amplify";
import { useEffect } from "react";
import awsconfig from "../amplifyconfiguration.json"; // Generated by `amplify push`

import Navbar from "../components/Navbar";
import { ToastContainer } from "react-toastify";
import Head from "next/head";
import { navBarData } from "@/utils/data/navbar/navbarData";

// Configure Amplify with SSR support
Amplify.configure({ ...awsconfig, ssr: true });

export default function App({ Component, pageProps }) {
  const router = useRouter();

  // Track page views on route changes
  useEffect(() => {
    // Track initial page load
    Analytics.record({
      name: "pageView",
      attributes: { path: router.pathname },
    });

    // Track subsequent route changes
    const handleRouteChange = (url) => {
      Analytics.record({
        name: "pageView",
        attributes: { path: url },
      });
    };

    router.events.on("routeChangeComplete", handleRouteChange);

    // Cleanup on unmount
    return () => {
      router.events.off("routeChangeComplete", handleRouteChange);
    };
  }, [router]);

  return (
    <AnimatePresence mode="wait">
      <motion.div key={router.pathname} className={"h-auto"}>
        <Head>
          <link rel="shortcut icon" href="/favicon.png" />
        </Head>
        <Navbar menuItems={navBarData} />
        <Component {...pageProps} />
        <ToastContainer />
        <motion.div
          className="absolute top-0 left-0 w-screen h-screen bg-black z-50"
          initial={{ scaleY: 0 }}
          animate={{ scaleY: 0 }}
          exit={{ scaleY: 1 }}
          transition={{ duration: 0.75, ease: [0.22, 1, 0.36, 1] }}
        />
      </motion.div>
    </AnimatePresence>
  );
}